import { NailArtDesign } from './types';

export const NAIL_ART_DESIGNS: NailArtDesign[] = [
  {
    id: 'cosmic-dream',
    name: 'Cosmic Dream',
    description: 'A mesmerizing galaxy-themed design with swirling nebulas, twinkling stars, and deep cosmic hues of purple and blue. Perfect for a night out under the stars.',
    prompt: 'Elegant galaxy nail art with deep blues, purples, and shimmering silver glitter that looks like stars and distant nebulas. The finish should be high-gloss.',
    image: 'https://picsum.photos/seed/cosmic/500/500',
    category: 'Abstract',
  },
  {
    id: 'floral-elegance',
    name: 'Floral Elegance',
    description: 'Delicate and sophisticated, this design features intricate cherry blossom branches painted over a soft, neutral base coat. A timeless choice for any occasion.',
    prompt: 'A delicate and minimalist nail art design featuring tiny, hand-painted cherry blossoms on a nude pink base. The style is subtle and elegant.',
    image: 'https://picsum.photos/seed/floral/500/500',
    category: 'Minimalist',
  },
  {
    id: 'chrome-future',
    name: 'Chrome Future',
    description: 'Embrace a futuristic vibe with this stunning liquid chrome finish. The nails reflect light with an intense, mirror-like shine that is both edgy and chic.',
    prompt: 'A futuristic, high-shine silver chrome manicure. The nails should look like they are dipped in liquid metal, with a flawless mirror-like reflection.',
    image: 'https://picsum.photos/seed/chrome/500/500',
    category: 'Modern',
  },
  {
    id: 'scarlet-classic',
    name: 'Scarlet Classic',
    description: 'You can never go wrong with a classic red. This design is a vibrant, glossy scarlet red that exudes confidence and timeless glamour.',
    prompt: 'A classic, flawless glossy red manicure. The color is a vibrant scarlet red. The nails are perfectly shaped and have a high-gloss, gel-like finish.',
    image: 'https://picsum.photos/seed/scarlet/500/500',
    category: 'Classic',
  },
  {
    id: 'ocean-waves',
    name: 'Ocean Waves',
    description: 'Capture the beauty of the sea with this design inspired by ocean waves. It features shades of blue and white, creating a dynamic, flowing pattern reminiscent of waves crashing on the shore.',
    prompt: 'Nail art that looks like crashing ocean waves. Use shades of deep blue, turquoise, and frothy white to create a realistic wave effect with a glossy finish.',
    image: 'https://picsum.photos/seed/ocean/500/500',
    category: 'Nature',
  },
  {
    id: 'matte-midnight',
    name: 'Matte Midnight',
    description: 'A sophisticated and understated design. This is a deep, velvety matte black finish that is both modern and mysterious.',
    prompt: 'A chic and modern solid matte black manicure. The finish is completely flat, with no shine, for a velvety, sophisticated look.',
    image: 'https://picsum.photos/seed/matte/500/500',
    category: 'Modern',
  },
  {
    id: 'golden-glitter',
    name: 'Golden Glitter Fade',
    description: 'Add some sparkle to your life! This design features a beautiful gradient of fine golden glitter, fading from the tip towards the cuticle over a neutral base.',
    prompt: 'An elegant glitter fade nail art. Start with a sheer nude base and apply fine gold glitter that is dense at the nail tip and fades out towards the cuticle.',
    image: 'https://picsum.photos/seed/glitter/500/500',
    category: 'Glamour',
  },
  {
    id: 'pastel-dreams',
    name: 'Pastel Dreams',
    description: 'Soft and dreamy, this design uses a blend of pastel colors like baby blue, soft pink, and lavender in a subtle marbled pattern.',
    prompt: 'A dreamy pastel watercolor or marble nail art design. Gently blend shades of baby blue, soft pink, mint green, and lavender for a soft, ethereal effect.',
    image: 'https://picsum.photos/seed/pastel/500/500',
    category: 'Abstract',
  },
  {
    id: 'geometric-lines',
    name: 'Geometric Lines',
    description: 'A clean and modern design featuring sharp, contrasting lines for a bold, architectural look.',
    prompt: 'Minimalist geometric nail art with clean black lines over a matte white base. The design is precise and sharp.',
    image: 'https://picsum.photos/seed/geometric/500/500',
    category: 'Geometric',
  },
  {
    id: 'autumn-warmth',
    name: 'Autumn Warmth',
    description: 'Embrace the cozy feeling of autumn with warm hues of orange, brown, and gold, perhaps with a subtle leaf motif.',
    prompt: 'Nail art inspired by autumn leaves. A gradient of warm colors like burnt orange, deep red, and gold shimmer. A single delicate leaf accent on one nail.',
    image: 'https://picsum.photos/seed/autumn/500/500',
    category: 'Seasonal',
  },
  {
    id: 'french-twist',
    name: 'French Twist',
    description: 'A modern take on the classic French manicure, using a thin, colorful tip instead of the traditional white.',
    prompt: 'A modern French manicure with a very thin, delicate line of pastel blue at the tip of the nails on a sheer, natural base.',
    image: 'https://picsum.photos/seed/french/500/500',
    category: 'Minimalist',
  },
  {
    id: 'starry-night',
    name: 'Starry Night',
    description: 'A playful and enchanting design with tiny stars and moons scattered across a deep navy blue base.',
    prompt: 'A whimsical starry night sky nail art. A deep navy blue base with tiny hand-painted white and silver stars, and a crescent moon accent.',
    image: 'https://picsum.photos/seed/starry/500/500',
    category: 'Whimsical',
  },
  {
    id: 'watercolor-splash',
    name: 'Watercolor Splash',
    description: 'A vibrant and artistic design that mimics watercolor paint bleeding on a canvas, with soft edges and beautiful color blends.',
    prompt: 'Artistic watercolor nail art with splashes of pink, purple, and blue bleeding into each other on a white base. The effect is soft and dreamy.',
    image: 'https://picsum.photos/seed/watercolor/500/500',
    category: 'Abstract',
  },
  {
    id: 'negative-space-chic',
    name: 'Negative Space Chic',
    description: 'A minimalist and modern design that uses the natural nail as part of the artwork, with geometric shapes and lines on a clear base.',
    prompt: 'Modern negative space nail art. A clear, glossy base with a single, clean white crescent shape near the cuticle. Minimalist and chic.',
    image: 'https://picsum.photos/seed/negativespace/500/500',
    category: 'Modern',
  },
  {
    id: 'marble-stone',
    name: 'Marble Stone',
    description: 'An elegant and timeless design that mimics the natural veining of white and grey marble, perfect for a sophisticated look.',
    prompt: 'Realistic white marble nail art with delicate grey veins. The finish is high-gloss, resembling polished stone.',
    image: 'https://picsum.photos/seed/marble/500/500',
    category: 'Nature',
  },
  {
    id: 'holographic-shards',
    name: 'Holographic Shards',
    description: 'An eye-catching design with iridescent shards that reflect a rainbow of colors, creating a shattered glass effect over a dark base.',
    prompt: 'Shattered glass nail art using holographic film shards over a glossy black base. The shards should reflect a rainbow of colors when they catch the light.',
    image: 'https://picsum.photos/seed/holographic/500/500',
    category: 'Modern',
  },
  {
    id: 'pressed-flowers',
    name: 'Pressed Flowers',
    description: 'A delicate and romantic design featuring tiny, real dried flowers encapsulated in a clear gel for a beautiful, botanical look.',
    prompt: 'Delicate pressed flower nail art. A sheer, milky white base with tiny, real dried multi-colored flowers carefully placed and encapsulated in clear gel.',
    image: 'https://picsum.photos/seed/pressedflowers/500/500',
    category: 'Nature',
  },
  {
    id: 'ruby-red-glitter',
    name: 'Ruby Red Glitter',
    description: 'A dazzling full-coverage glitter nail in a deep ruby red shade. Perfect for parties, holidays, or any time you want to make a statement.',
    prompt: 'A full coverage, high-density ruby red glitter nail polish. The glitter is fine and intensely sparkly, creating a dazzling, jewel-like effect.',
    image: 'https://picsum.photos/seed/rubyglitter/500/500',
    category: 'Glamour',
  },
  {
    id: 'ink-drop-noir',
    name: 'Ink Drop Noir',
    description: 'A dramatic and sophisticated design featuring black ink drops blooming in a clear or nude base, creating a smoky, ethereal effect.',
    prompt: 'Smoky black ink drop nail art. A translucent nude base with black alcohol ink blooming outwards in delicate, smoky patterns. A touch of gold foil.',
    image: 'https://picsum.photos/seed/inkdrop/500/500',
    category: 'Abstract',
  },
];