import React from 'react';

interface FreeDownloadBannerProps {
  designName: string;
  category: string;
  downloadUrl: string;
  sourceUrl: string;
  className?: string;
}

export default function FreeDownloadBanner({
  designName,
  category,
  downloadUrl,
  sourceUrl,
  className = ''
}: FreeDownloadBannerProps) {
  return (
    <div className={`bg-gradient-to-r from-purple-600 to-pink-600 text-white p-6 md:p-8 lg:p-10 md:p-8 rounded-lg shadow-lg ${className}`}>
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex-1">
          <h3 className="text-lg font-bold mb-2">
            🎨 Free {category} Nail Art Design
          </h3>
          <p className="text-sm opacity-90 mb-2">
            <strong>{designName}</strong> by nailartai.app
          </p>
          <div className="flex flex-wrap gap-2 text-xs">
            <span className="bg-white/20 px-2 py-1 rounded">✅ Commercial Use</span>
            <span className="bg-white/20 px-2 py-1 rounded">✅ No Attribution</span>
            <span className="bg-white/20 px-2 py-1 rounded">✅ Download Free</span>
          </div>
        </div>
        <div className="flex gap-2">
          <a
            href={downloadUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="bg-white text-purple-600 px-4 py-2 rounded font-semibold hover:bg-gray-100 transition-colors"
          >
            Download
          </a>
          <a
            href={sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="bg-purple-700 text-white px-4 py-2 rounded font-semibold hover:bg-purple-800 transition-colors"
          >
            View Design
          </a>
        </div>
      </div>
    </div>
  );
}

export function FreeDownloadInfo() {
  return (
    <div className="bg-green-50 border border-green-200 rounded-lg p-6 md:p-8 lg:p-10 md:p-8 mb-6">
      <div className="flex items-start gap-3">
        <div className="text-green-600 text-2xl">🎨</div>
        <div>
          <h3 className="text-lg font-semibold text-green-800 mb-2">
            All Designs Are Free to Use!
          </h3>
          <p className="text-green-700 mb-3">
            Every nail art design generated by nailartai.app is free for commercial use with no attribution required.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm">
            <div className="flex items-center gap-2">
              <span className="text-green-600">✅</span>
              <span>Commercial use allowed</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-600">✅</span>
              <span>No attribution required</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-600">✅</span>
              <span>Modify and adapt freely</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-green-600">✅</span>
              <span>Share without restrictions</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function LicenseInfo() {
  return (
    <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 md:p-8 lg:p-10 md:p-8 text-sm">
      <div className="flex items-start gap-2">
        <span className="text-blue-600 text-lg">ℹ️</span>
        <div>
          <p className="text-blue-800 font-medium mb-1">License Information</p>
          <p className="text-blue-700">
            All nail art designs are released under <strong>CC0-1.0 (Public Domain)</strong> license. 
            This means you can use them for any purpose without restrictions.
          </p>
          <p className="text-blue-600 mt-2">
            <a 
              href="https://creativecommons.org/publicdomain/zero/1.0/" 
              target="_blank" 
              rel="noopener noreferrer"
              className="underline hover:no-underline"
            >
              Learn more about CC0 license →
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
